# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Fluffy Game Reviews
description:      'Testing templates for game review site'
url:              https://github.com/LordFluffyPants
baseurl:          /

author:
  name:           'Jake Hayhurst'


paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/LordFluffyPants
