# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            BOE Reviews
description:      'The best opinions ever on the internet'
tagline: 		      Best Opinions Ever
baseurl:          "/"

author:
  name:           'Jake Hayhurst'


paginate:         5

# Custom vars
version:          1.1.0
gems: [jekyll-paginate]
